### ISSUE TITLE
Thanks, and also a library recommendation

### ISSUE THREAD

**Issue by qdot** [elliotcubit/WebfishingButtplug#2]
Yo. qDot from buttplug.io here. Thanks for getting this done! There's been discussion of getting a webfishing mod done on my discord but I think we were all too lazy lol.

Anyways, the buttplug client you're using *should* work fine, but hasn't been updated in years. If you decide you wanna take this project any farther, might check out [gspot](https://github.com/deadpixelsociety/gspot), which is still kept up.

Also plz lemme know if you run into any issues with buttplug/intiface/etc, happy to help out where I can.

Also also ffs put your kofi or patreon in your README. :3

**Comment by elliotcubit** [comment]
> Thanks for getting this done!

 I've been meaning to build something with buttplug.io for a while, so I was excited to work on this.

> might check out [gspot](https://github.com/deadpixelsociety/gspot), which is still kept up.

Thanks very much for the suggestion! This was a project for a few spare hours I had, so I'll go ahead and update to the better library SoonTM (I couldn't find it before!)

> Also also ffs put your kofi or patreon in your README. :3

Aw, thanks! I'm not in a place where I feel comfortable accepting money from people on the Internet, so please consider donating to [The Trevor Project](https://give.thetrevorproject.org/give/63307/#!/donation/checkout) or [The ACLU](https://action.aclu.org/give/now) if you feel passionately about giving me money. I added a relevant section to README.md, too. :)
