### ISSUE TITLE
IC not connecting to clinet

### ISSUE THREAD

**Issue by Sullykun** [elliotcubit/WebfishingButtplug#3]
Downloaded and installed as indicated on the page, but interface central is not detecting the game at all
![image](https://github.com/user-attachments/assets/674811b9-fcb1-444a-a33d-0f459832ed2b)

**Comment by Firerr** [comment]
I'd have to guess it's because of this
![Screenshot_104](https://github.com/user-attachments/assets/7956ac36-dcb2-4671-9421-a2b6e14de3e0)

**Comment by Firerr** [comment]
https://thunderstore.io/c/webfishing/p/PuppyGirl/TackleBox/

**Comment by elliotcubit** [comment]
Hi! @Firerr is indeed correct, this is because of a missing dependency. I added a feature to the mod in 1.1.0, and forgot to update the install instructions accordingly.

They are now updated (you just need to install the missing dependency). Thanks for filing the issue!
